// http://dougtesting.net/winwheel/docs/

import Head from 'next/head'
import Script from 'next/script'
import Wheel from '/components/Wheel'
import Sidebar from '/components/Sidebar'

import styles from '/styles/Home.module.scss'
import { useEffect, useState } from 'react';
import CustomFavicon from '../components/CustomFavicon'
import WinningSegmentScreen from '../components/WinningSegmentScreen'

export default function Home() {
  const [favi, setFavi] = useState(`/favicon/1.png`)
  const [theWheel, setTheWheel] = useState();
  const [winningSegment, setWinningSegment] = useState();
  const [segments, setSegments] = useState([
    { fillStyle: '#eae56f', text: 'Loading your favorites!' },
  ]);

  // Get segments from storage
  useEffect(() => {
    const firstSegment = { fillStyle: '#eae56f', text: 'Loading your favorites!' }
    const localSegments = localStorage.getItem('segments')

    let segments
    if (localSegments) {
      const parsedLocalSegments = JSON.parse(localSegments)
      segments = parsedLocalSegments.filter(ls => {
        if (ls?.text !== '' && ls?.text !== firstSegment.text) return ls
      })
    }
    else {
      segments = firstSegment
    }

    const params = {
      pointerAngle: 0,
      numSegments: segments.length,
      fillStyle: '#e7706f',
      lineWidth: 1,
      segments,
      animation: {
        type: 'spinToStop',
        duration: 5, // In seconds
        spins: 8,
        callbackFinished: (winningSegment) => setWinningSegment(winningSegment.text),
      },
    };

    if (!theWheel) setTheWheel(new Winwheel(params));
  }, []);

  return (
    < >
      <Head>
        <title>Food wheel</title>
        <meta name="description" content="Generated by create next app" />
        <link id='icon' rel='icon' href={favi} />
      </Head>
      <CustomFavicon setFavi={setFavi} />

      <Script type='text/javascript' src='/Winwheel.js' strategy='beforeInteractive' />
      <Script type='text/javascript' src='/TweenMax.js' strategy='beforeInteractive' />

      <main id="main" className={`container-fluid h-100`}>
        <div className='row h-100'>
          <div className='col d-flex align-items-center'>
            <Wheel theWheel={theWheel} />
          </div>
          <div className='col-auto g-0'>
            <Sidebar theWheel={theWheel} segments={segments} setSegments={setSegments} />
          </div>
        </div>

        {winningSegment && <WinningSegmentScreen winningSegment={winningSegment} onHide={() => setWinningSegment()} />}
      </main>

      <footer className={styles.footer}>
        Made with 🍕 by {' '}
        <span id={styles.jeramai}>
          Jeram.ai
        </span>
      </footer>
    </>
  )
}
