import Head from 'next/head'
import Script from 'next/script'
import { useState } from 'react'
import Wheel from '/components/Wheel'

import styles from '/styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <script type="text/javascript" src='/Winwheel.js' ></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js" ></script>
      </Head>

      <main id="main" className={styles.main}>
        <Wheel />

        <div className={styles.grid}>
          <a
            href="/recipe/add"
            className={styles.card}
          >
            <h2>Add recipe &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

          <a
            href="/recipe/edit"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Made with 🍕 by {' '}
        <span>
          Jeramai
        </span>
      </footer>
    </div>
  )
}
